### ISSUE TITLE
七牛云无法上传，感觉配置没有问题。

### ISSUE THREAD

**Issue by dengjiaming** [xiebruce/PicUploader#1]
Qiniu\Http\Error::__set_state(array(
   'url' => 'http://',
   'response' => 
  Qiniu\Http\Response::__set_state(array(
     'statusCode' => -1,
     'headers' => 
    array (
    ),
     'body' => NULL,
     'error' => 'Bad URL',
     'jsonData' => NULL,
     'duration' => 0.0,
  )),
))

**Comment by xiebruce** [comment]
@dengjiaming 代码更新到最新了吗？我后来又更新过

**Comment by dengjiaming** [comment]
git clone git@github.com:xiebruce/PicUploader.git
直接下载 PicUploader

用第一个方法下载可以，建议更新下第二个方法的包。

**Comment by xiebruce** [comment]
@dengjiaming 好的，那就是没问题了？你现在可以正常上传了对吗？

**Comment by dengjiaming** [comment]
嗯嗯，可以了

**Comment by dengjiaming** [comment]
> @dengjiaming 好的，那就是没问题了？你现在可以正常上传了对吗？
