### ISSUE TITLE
BUG：开启水印之后关闭水印依然有水印

### ISSUE THREAD

**Issue by XinAnzzZ** [xiebruce/PicUploader#10]
BUG：开启水印之后关闭水印依然有水印

**Comment by xiebruce** [comment]
@XinAnzzZ 已解决，请更新刷新后台页面再试。

**Comment by XinAnzzZ** [comment]
感谢！！另外图片压缩设置到 100%还是会自动压缩，求解如何设置。
![image](https://user-images.githubusercontent.com/38024683/57768924-3ce81b00-773f-11e9-95cb-9ab3ca14a93d.png)

**Comment by XinAnzzZ** [comment]
我的图片已经压缩过了，自动压缩会导致图片质量变得特别低，所以不希望压缩。另外，在设置优化的参数那里也把全部的参数都删除了。
![image](https://user-images.githubusercontent.com/38024683/57769043-820c4d00-773f-11e9-995c-67ef1224eb7c.png)

**Comment by xiebruce** [comment]
@XinAnzzZ 压缩百分比设置为100%是不会压缩的，但是，你有没有设置水印？图片是jpg还是png？

**Comment by XinAnzzZ** [comment]
是 JPG 格式的。我之前设置过压缩，但是后面发现压缩之后质量太差  所以改成了 100，但是还是会压缩，只是压缩的比例没之前那么严重了。之前 150k会压缩到 20 多 k，但是修改为 100 之后会压缩到 70K，是同一张图片测试的。

**Comment by xiebruce** [comment]
@XinAnzzZ 水印，你有没有设置添加水印？

**Comment by XinAnzzZ** [comment]
之前设置了，后面关闭了还是有水印，那估计是因为加水印的问题导致了图片压缩。我再去测试一下。

**Comment by XinAnzzZ** [comment]
我拉了新代码测试了一下，水印的问题解决了，图片似乎没有被压缩，但是不知道是因为 mac 电脑的问题还是被压缩的问题，上传后的图片比原图少了大概 10K。但是问题不大，几乎没什么影响。感谢大佬。

**Comment by xiebruce** [comment]
@XinAnzzZ 

1、关于Mac和Linux/Windows文件大小问题
如果你是在mac上上传到七牛后，在七牛上看的大小小了一点，那么这是完全正常的，因为一般情况下，这个多少K/M/G/T都是1024进位的(Linux/Windows都是1024)，但是mac不是，mac是1000进位的，假设你的图片在mac上是150KB=150*1000=150000 Byte(字节，注意，我前面说了，mac上是1000进位的)，那么在linux上看，它的大小是多少K呢？是150000 Byte ÷ 1024 = 146.484375 ≈ 146K，这就小了4k，图片越大，这个差距越明显，比如你mac上是1.5M，那么转成字节是 1.5*1000*1000=1500000 Byte，在Linux上看，是 1500000 ÷ 1024 ÷ 1024 = 1.43M，其实真正大小是没变的，转成字节，在什么系统都一样大，只是转成K/M/G/T时，因为除的进位不同，所以看上去数字不同。
<hr>
2、就算你没设置图片压缩，但如果你设置了水印，大小还是会有变化的，因为添加水印其实是“重新生成图片”的过程，生成图片会有一个质量参数，就算你设置100%，它好像还是会有变化的，这个我是无法控制的，但设置100%的话，应该不会对图片质量不会有什么影响。

**Comment by XinAnzzZ** [comment]
懂了，感谢大佬解答。谢谢！！！
