### ISSUE TITLE
Mac自动操作异常

### ISSUE THREAD

**Issue by yintianyu** [xiebruce/PicUploader#11]
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 14 unable to open database file in /Users/yintianyu/code/Github/PicUploader/settings/DbModel.php:101
Stack trace:
#0 /Users/yintianyu/code/Github/PicUploader/settings/DbModel.php(101): PDO->exec('INSERT INTO `hi...')
#1 /Users/yintianyu/code/Github/PicUploader/settings/HistoryModel.php(33): settings\DbModel->execute('INSERT INTO `hi...')
#2 /Users/yintianyu/code/Github/PicUploader/settings/HistoryController.php(33): settings\HistoryModel->createOne(Array)
#3 /Users/yintianyu/code/Github/PicUploader/uploader/Upload.php(141): settings\HistoryController->Add('IMG_88F82B209BE...', 'http://pictures...', 375285)
#4 /Users/yintianyu/code/Github/PicUploader/index.php(105): uploader\Upload->getPublickLink(Array)
#5 {main}
  thrown in /Users/yintianyu/code/Github/PicUploader/settings/DbModel.php on line 101

**Comment by xiebruce** [comment]
你检查一下把PicUploaer整个文件夹的所有者和所属组，要求设置为：Mac用户名:staff，“Mac用户名”获取方法——在终端上输入“whoami”，回车即可！比如你的Mac用户名是`zhangsan`，那么设置所有者和所属组的命令为：
```
chown -R zhangsan:staff ./PicUploader
```

**Comment by yintianyu** [comment]
> 你检查一下PicUploaer整个文件夹的所有者和所属组，要求设置为：Mac用户名:staff，“Mac用户名”获取方法——在终端上输入“whoami”，回车即可！比如你的Mac用户名是`yintianyu`，那么设置所有者和所属组的命令为：
> 
> 先进入PicUploader所在目录：
> 
> ```
> cd /Users/yintianyu/code/Github
> ```
> 
> 然后设置PicUploader的所有者和所属组：
> 
> ```
> sudo chown -R yintianyu:staff ./PicUploader
> ```

是有两个目录的所属是root，改过来就好了

**Comment by xiebruce** [comment]
@yintianyu 嗯嗯，好了就好，好用的话给个star呀！
