### ISSUE TITLE
部署在远程服务器

### ISSUE THREAD

**Issue by ItsnotMango** [xiebruce/PicUploader#13]
你好，
    请问部署在远程服务器以后怎么打开后台呢？

**Comment by xiebruce** [comment]
后台是一个网页，当然是通过域名打开了(说白了就是通过“网址”打开)，网址是什么？你自己定呀。两种方法：
1. 如果在本地部署，不是要修改`hosts`文件，在里面写上：
```
127.0.0.1       api.picuploader.com
```
其中这意思就是告诉浏览器，`api.picuploader.com`这个“网址”对应的ip是“127.0.0.1”，也就是本机ip（为什么127.0.0.1是本机ip，这是规定的，任何电脑/手机上的127.0.0.1都表示本机）

而现在你部署到了服务器上，你服务器肯定有一个ip吧？假设你服务器ip是`23.45.67.78`，那么你只要把hosts文件改成下面这样就ok了：
```
23.45.67.78       api.picuploader.com
```

---

2. 第1种方法需要你在每台要访问`api.picuploader.com`的电脑上都修改hosts文件并填上上述所说的内容，否则是打不开的。如果你不想这样，那就得注册一个域名，然后在域名注册服务商(比如阿里云)那里是可以指定你的域名对应的ip的，当然域名就不可能是`api.picuploader.com`了，比如你注册的域名是`example.com`，那你就添加一条`www.example.com`的记录，把它指向你服务器的ip`23.45.67.78`就行了。不过注册的域名是要认证也是要花钱的(每年都要交线)。

**Comment by ItsnotMango** [comment]
好的，谢谢大佬
