### ISSUE TITLE
我在服务器上搭了一个WEB版能直接快捷键调用接口吗？

### ISSUE THREAD

**Issue by singworld** [xiebruce/PicUploader#14]
mac和Windows可以实现吗     把index.php换成服务器地址 前面的/usr/bin/php换成什么
/usr/bin/php /Users/xxxxx/www/PicUploader-master/index.php 
windows上php_path"是php.exe
服务器web版有密码

**Comment by xiebruce** [comment]
不行，快捷键的本质是调用脚本，而不是调用接口，你要用快捷键那就把代码部署在本地就行了，Mac的话配合Alfred还是很好用的
