### ISSUE TITLE
怎样加入后台管理页面，或者对接口页面的保护之类的

### ISSUE THREAD

**Issue by PlutoTz** [xiebruce/PicUploader#15]
比如说我在vps部署完毕后，输入域名，进入的是图床上传界面，但是不能设置接口，不能查看接口密钥之类的，这样可以把链接放出去分享给其他人用。只有进去后台管理才能拥有权限进行相应的设置。
或者直接简单的加入用户密码保护，不用ngnix实现，用php html这种，怎么弄呢，请求大佬指教，我感觉这个picuploader目前来说对私有云储存太好了，就差这个功能了

**Comment by xiebruce** [comment]
@PlutoTz 我没有做这功能哦，完全没有做这功能，本来我这个是在本地用的，后来觉得频繁改配置直接修改配置文件很麻烦也不直观，所以就写了个简单的页面，后来越写越多，既加入了网页上传，又加入了上传历史记录页面，不要把我这个当成是网盘系统啊，这还差的远呢。你要的功能，如果你自己会的话就自己加呗，反正源码在这里，不会的话，就看我什么时候有时间搞一下了，我本来是没打算搞这个的。

**Comment by PlutoTz** [comment]
希望大佬有时间添加，我感觉这个项目好好做下去，真的很好，我自己在私下琢磨琢磨，毕竟我也刚接触这面的知识不是特别懂  麻烦了

**Comment by xiebruce** [comment]
后面再看看吧，其实不太清楚你为什么要给其他人用，因为我这本身是用于自己上传图片到微博、又拍云之类的然后给自己的博客或md文档贴图用的，你给别人用那不就相当于提供在线图床服务了？这样的图床有很多，你可以github上找找，我本身写这个的目的不是为了提供图床服务！

**Comment by PlutoTz** [comment]
我懂这个意思，给别人用不用我是这样说的，如果违背了你的目的那说声抱歉，只是我自己的想法，希望你做的越来越好，能够融入管理系统，我会静静期待，给你个star   哈哈😄

**Comment by xiebruce** [comment]
好的，谢谢，管理系统的话，再看吧哈哈，但这个项目肯定一直维护的，因为我自己在用并且会一直用(因为我博客需要)。
