### ISSUE TITLE
帮我看下错误

### ISSUE THREAD

**Issue by xhmily** [xiebruce/PicUploader#16]
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations:
  CAfile: ‪C:\phpStudy\PHPTutorial\php\php-7.2.1-nts\cacert.pem
  CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in C:\phpStudy\PHPTutorial\WWW\PicUploader\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:186
Stack trace:
#0 C:\phpStudy\PHPTutorial\WWW\PicUploader\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 C:\phpStudy\PHPTutorial\WWW\PicUploader\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 C:\phpStudy\PHPTutorial\WWW\PicUploader\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\ in C:\phpStudy\PHPTutorial\WWW\PicUploader\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 186

**Comment by xiebruce** [comment]
在我[博客文档](https://www.xiebruce.top/17.html)中页内搜索“在使用微博/Imgur/Github/smms做图床时，可能会有以下报错”，里面有说。

**Comment by xhmily** [comment]
正是因为我照做了，所以报错是 77 而不是 60 啊

**Comment by xiebruce** [comment]
你用的哪个云？

**Comment by xhmily** [comment]
github

**Comment by xiebruce** [comment]
你有科学上网工具吗？设置个代理试试，有可能是这问题，不要认为你直接能访问github就一定不需要科学上网，你先试试。

**Comment by xhmily** [comment]
我把工具开全局也是报这个错

**Comment by xiebruce** [comment]
不要用全局，php内部发起的curl请求貌似不会走全局的，还是在配置里设置吧，具体看config：
```
'proxy' => 'http://127.0.0.1:1087',
```
其中1087不一定是1087，要看你自己的端口

**Comment by xhmily** [comment]
不行，还是这样，不过我发现个问题，把Apache关掉也是这个错误，是不是我环境哪里错了

**Comment by xiebruce** [comment]
你是怎么上传？右击上传吗？右击上传跟apache没关系的

**Comment by xhmily** [comment]
哦哦，我就是右击上传，那我到底哪一步错了

**Comment by xhmily** [comment]
仓库用手动创建Images文件夹吗

**Comment by xiebruce** [comment]
不用手动创建的，你手动创建也可以

**Comment by xhmily** [comment]
搞了一天了，就是报错

**Comment by xiebruce** [comment]
你确定这个文件存在吗？`C:\phpStudy\PHPTutorial\php\php-7.2.1-nts\cacert.pem` ？
还把那个php.ini文件填`curl.cainfo=`部分截图给我看看。

**Comment by xhmily** [comment]
![image](https://user-images.githubusercontent.com/22665002/60765464-5b2e1f80-a0cd-11e9-94c5-3eb1c7267a4e.png)
![image](https://user-images.githubusercontent.com/22665002/60765475-7dc03880-a0cd-11e9-93cc-59a5ea68edde.png)
d都存在的

**Comment by xiebruce** [comment]
引号不是中文引号吧？

**Comment by xhmily** [comment]
肯定是英文的，我是学java的，这点会注意的，现在又开始报新错了 ，似乎环境没问题了，你看看

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://api.github.com/repos/xhmily/imgbed/contents/images/c26297c9820bf57e7277acfd37d0f769.jpg` resulted in a `404 Not Found` response:
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/contents/#create-or-update-a-f (truncated...)
 in F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\Task in F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by xiebruce** [comment]
这次就不是证书错误了，不过你这错误不应该呀，你那个路径我对比了一下，应该没问题呀，你现在没用代理了吧？如果有用的话，把配置的代理去掉，把全局代理也关掉再试试

**Comment by xhmily** [comment]
没用代理，都关掉了
github.com/xhmily/imgbed  这是我仓库
头疼了

**Comment by xiebruce** [comment]
你试试手动创建一个images文件夹，再来上传（但实际上是不需要手动创建的，不过还是试试吧）

**Comment by xhmily** [comment]
创建了也是不行

**Comment by xiebruce** [comment]
那就神奇了，你找到这个文件`uploader/UploadGithub.php`，然后添加一个输出：
```php
$uri = $this->repo . '/contents/'. $key;
var_export($uri);exit;
```
然后再上传试试输出什么？

**Comment by xhmily** [comment]
可是加在哪行

**Comment by xiebruce** [comment]
这行是添加的`var_export($uri);exit;`，这行是原来的`$uri = $this->repo . '/contents/'. $key;`，你只要找到原来那行，在它下面添加就行，在90多行

**Comment by xhmily** [comment]
输出这个   'xhmily/imgbed/contents/images/81cfc40a15185398d0b46a62538a7dd1.jpg'

**Comment by xiebruce** [comment]
好，添加那行去掉吧，或者用`//`注释掉，我先看看是怎么回事

**Comment by xiebruce** [comment]
把你配置github的那个配置截图给我看看，access_token你模糊一下就行，其他参数不是什么敏感参数

**Comment by xhmily** [comment]
![image](https://user-images.githubusercontent.com/22665002/60765850-40f74000-a0d3-11e9-902e-5b7a00a474ad.png)

**Comment by xiebruce** [comment]
你的网页版有没有配置起来？现在要确定一下，配置读的是哪个配置，如果你用了网页版的，那它会读网页版的那个配置，如果没有用网页版，它会读`config-local.php`，如果没有`config-local.php`，它会读`config.php`，你现在这个是哪个文件？

**Comment by xhmily** [comment]
网页版没弄，Apache都没启动，现在是config-local.php配置了 ，源文件没改动

**Comment by xiebruce** [comment]
有没可能是token权限问题？不过如果token权限貌似也不应该报这错呀，你能不能把token给我用一下试试？发上来也没事，反正你可以删掉重新生成一个。

**Comment by xhmily** [comment]
5d35af23054bcf044c3d670a692b9eb8e7092c4e 去试吧

**Comment by xiebruce** [comment]
果然我用你的不行，应该就是token权限问题了，我的token权限这样的，你按我这弄试试：
![image](https://user-images.githubusercontent.com/13575500/60766044-35f1df00-a0d6-11e9-8ea0-346244ed3025.png)

**Comment by xiebruce** [comment]
最新测试，只要这几个权限就够了，不需要其他(我现在也把其它权限去掉了)：
![image](https://user-images.githubusercontent.com/13575500/60766094-20c98000-a0d7-11e9-9c4c-fa208fa453c3.png)

**Comment by xiebruce** [comment]
怎么样，可以了不？

**Comment by xhmily** [comment]
按照你的权限重新生成，然后这是结果.....

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `PUT https://api.github.com/repos/xhmily/imgbed/contents/images/e28f1bcf7ba255c58c055d0c647d9289.jpg` resulted in a `401 Unauthorized` response:
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

 in F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 F:\PicUploader\PicUploader\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promi in F:\PicUploader\PicUploader\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

**Comment by xiebruce** [comment]
那你就加权限，先全部勾上，看行不行，行了再慢慢减吧，这401就是权限问题

**Comment by xhmily** [comment]
![Automata.jpg](https://raw.githubusercontent.com/xhmily/imgbed/master/images/8dee30048b7b14abd199ba23958b9e4d.jpg)

好了非常感谢，还是所有权限最保险，star了

**Comment by xiebruce** [comment]
好的谢谢，终于可以了，不过现在我还是没明白，你的cainfo证书那个报错，是怎么好的？自己好的还是你之前填错了什么？

**Comment by xhmily** [comment]
没有填错，可能是重新填过一次，不清楚，明明操作一样，文件也还是昨晚下载的那个，只是今天重新复制了一下路径而已啊

**Comment by xiebruce** [comment]
那我怀疑还是路径的问题，可能某个小错误你没发现，例如一个空格或者一个隐藏的什么符号，有时候很诡异的，毕竟你这错误就是报的“error setting certificate verify **locations**”：
![image](https://user-images.githubusercontent.com/13575500/60766680-cbde3780-a0df-11e9-8ad4-47575a92e2e6.png)

**Comment by xhmily** [comment]
可能是这样

**Comment by xiebruce** [comment]
嗯，不管怎样，反正现在可以了哈哈，网页版搞起来，修改配置会比较方便，我更新了一下，添加了对[Cloudinary](https://cloudinary.com)的支持！

**Comment by xhmily** [comment]
嗯，不过那些杂七杂八的容器不敢用，指不定哪天图片没了或者公司倒了，反正我只用腾讯阿里GitHub

**Comment by xiebruce** [comment]
我这个PicUploader是可以同时上传多个的，不太可能好几个一起倒闭。

**Comment by xhmily** [comment]
反正GitHub最稳，话说这样正常吗
![image](https://user-images.githubusercontent.com/22665002/60767010-e0bcca00-a0e3-11e9-8241-458bf39ac810.png)
![image](https://user-images.githubusercontent.com/22665002/60767017-f29e6d00-a0e3-11e9-88f9-7c3ab82fea14.png)

**Comment by xiebruce** [comment]
这不正常啊，应该替换成年月日才对，我查查我这里吧，刚才我试的时候还没问题的

**Comment by xhmily** [comment]
对啊，我也是按照你博客填的，是不是还有其他设置

**Comment by xiebruce** [comment]
你在这文件`settings/SettingController.php`里添加一句：
```
var_export($storageTypes[$key]['directory']);exit;
```
添加的位置：
![image](https://user-images.githubusercontent.com/13575500/60767185-b3255000-a0e6-11e9-8fec-0f2cb108f532.png)

**Comment by xhmily** [comment]
还是这样，没有输出

**Comment by xiebruce** [comment]
我后来又编辑了一下你看到了吧？在if前面加也没输出吗？

**Comment by xhmily** [comment]
![image](https://user-images.githubusercontent.com/22665002/60767296-b4577c80-a0e8-11e9-8640-34261e8d74eb.png)
竟然还是没有输出

**Comment by xiebruce** [comment]
这是个bug，我修复了，你把调试的语句去掉吧，然后更新一下就好了

**Comment by xhmily** [comment]
git pull??

**Comment by xiebruce** [comment]
对呀，如果你不是用git clone方式下载的，建议重新用git clone的方式下载，这样随时有更新都可以git pull更新。

**Comment by xhmily** [comment]
ok了，解决了谢谢

**Comment by xiebruce** [comment]
没事，因为我这用的web版的配置，所以直接用配置文件的我就没发现
