### ISSUE TITLE
你好，又是我

### ISSUE THREAD

**Issue by xhmily** [xiebruce/PicUploader#17]
请问你有没有遇到过快捷键上传没搞好，右击上传却不能用的情况？？？
我现在右击上传，cmd一闪就没了（不到1秒），剪贴板也没东西

**Comment by xiebruce** [comment]
你到`logs/2019/07`目录下找日志，应该会有`2019-07-08-error-log.txt`这样一个文件，看里面是什么内容

**Comment by xhmily** [comment]
里面没有错误只有这些，这是我快捷键上传的产物，可是当时没有消息提示，剪贴板也没东西
![image](https://user-images.githubusercontent.com/22665002/60793837-0e187f00-a19b-11e9-93a4-f6d76a761de5.png)

**Comment by xiebruce** [comment]
不是`.md`结尾的，`.md`结尾的是上传日志文件，没有`xxx-error-log.txt`结尾的吗？

**Comment by xhmily** [comment]
只有这些
![image](https://user-images.githubusercontent.com/22665002/60793954-4f109380-a19b-11e9-935c-d82c1f651284.png)

**Comment by xiebruce** [comment]
那就是没有错误文件，闪一下就没有，你粘贴没东西出来是吧？

**Comment by xhmily** [comment]
是的，没有东西，就像快捷键那样，不过快捷键竟然上传成功了

**Comment by xiebruce** [comment]
呃……这样啊，那你进注册表检查一下注册表的命令是怎样的：
![image](https://user-images.githubusercontent.com/13575500/60794349-2ccb4580-a19c-11e9-8ebc-d6ed51f25179.png)

**Comment by xhmily** [comment]
没错吧
![image](https://user-images.githubusercontent.com/22665002/60794578-a2cfac80-a19c-11e9-96d2-eccdd8016ebd.png)

**Comment by xiebruce** [comment]
你这样在cmd里手动执行试试，如果正常，它会直接在cmd输出上传成功后返回的md格式地址(注意要把路径参数改成你自己的，图片也要用绝对路径)：
```
D:\phpStudy\PHPTutorial\php\php-7.2.1-nts\php.exe "D:\phpStudy\PHPTutorial\WWW\PicUploader\index.php" "C:\Users\Bruce\Pictures\cats\13.jpg"
```

**Comment by xhmily** [comment]
![image](https://user-images.githubusercontent.com/22665002/60795671-a49a6f80-a19e-11e9-9631-03acf51d11b9.png)
这样可以

**Comment by xiebruce** [comment]
呃，这样可以，右击却会闪一下，那就奇怪了，那个，你首先试试换一个英文名字的图片(数字什么的都可以，反正别有中文)，然后试试右击上传是否正常？

如果还是不正常，那试试把注册表这个记录删除：
![image](https://user-images.githubusercontent.com/13575500/60795811-f511cd00-a19e-11e9-9895-8064b274edba.png)

再重新安装一次右键菜单试试？或者重启大法重启一下电脑试试？因为右击其实就是执行那个命令，按道理不太可能不行呀。

**Comment by xhmily** [comment]
删掉注册表重装都试过了。。。Python也卸载了，都没解决...

**Comment by xiebruce** [comment]
1、这跟python应该没什么关系，因为右击只是调用那条命令而已；
2、另外，你昨天好好的，今天你是搞了什么操作吗？
3、你试试git pull更新一下，我昨天又修了个bug，不过你直接敲命令都可以，按道理不应该是那个bug的问题，不过你还是更新一下再试试吧。

**Comment by xhmily** [comment]
能试的我都试过了，更新了也不行，今天就是试着装了一下快捷键那个，可是那个只是上传了，没消息，剪贴板也没东西，应该不是代码的问题吧

**Comment by xiebruce** [comment]
直接在cmd用命令都可以传，应该不是php代码问题，因为如果php代码有问题，你直接执行命令也是会报错的，我也想不出来是哪有问题了。

至于快捷键剪贴板没东西，那就是python安装的问题了，你方便的话，我可以远程帮你看看，加微信：xiediebruce

**Comment by xiebruce** [comment]
已经使用新方法获取剪贴板图片及设置快捷键，不需要安装Python了，比原来方便多了，具体请查看：[在Windows上使用PicUploader](https://www.xiebruce.top/1095.html)。
