### ISSUE TITLE
存储路径和上上传路径不对导致上传失败

### ISSUE THREAD

**Issue by MrJiao** [xiebruce/PicUploader#18]
使用alfred通过python上传github时报以下错误。初步排查临时文件存储路径和UploaderGithub.php 查找上传文件路径对不上
Warning: file_get_contents(/Users/jiaoyubing/Work/脚本/jackson-脚本/PicUploader/.tmp/.7dc18ac36be03e5c9b9978f6df02f570.png): failed to open stream: No such file or directory in /Users/jiaoyubing/Work/脚本/jackson-脚本/PicUploader/uploader/UploadGithub.php on line 98
![screenshot](https://raw.githubusercontent.com/MrJiao/markdown/master/img/486a02c34012987b01bc614535baee37.png?token=AC5VGGTWBNX57L6TE5ANHVC5IKFQS)

**Comment by xiebruce** [comment]
1、你的图片我看不见
2、你是右击图片上传的吗？还是用什么方式上传的？
3、你的代码是否为最新代码？如果不是请更新(直接`git pull`更新就行)

**Comment by MrJiao** [comment]
问题已经更新

**Comment by xiebruce** [comment]
好的，我看看

**Comment by xiebruce** [comment]
根据我判断，你的代码应该不是最新代码吧？更新到最新，就不会有问题

**Comment by MrJiao** [comment]
![screenshot](/Users/jiaoyubing/Work/脚本/jackson-脚本/PicUploader/.tmp/.9f647204cb374ea756b9305232f05301.png file does not exist)

**Comment by xiebruce** [comment]
你每次都一样用吗？都是截图到剪贴板直接用Alfred快捷键粘贴？

**Comment by MrJiao** [comment]
是的

**Comment by xiebruce** [comment]
方便远程吗？要不我远程看看，如果方便直接把Teamviewer的id和密码发上来就行，我还真没遇到过这问题

**Comment by MrJiao** [comment]
1 209 018 058
m1kp79

**Comment by xiebruce** [comment]
不行了，再来吧

**Comment by MrJiao** [comment]
号没变

**Comment by xiebruce** [comment]
这teamviewer，搞久点就认为是商业行为。。。
![image](https://user-images.githubusercontent.com/13575500/62303889-89760380-b4af-11e9-9883-eccf634f51c6.png)

**Comment by MrJiao** [comment]
你加我微信吧 Js_one1991

**Comment by xiebruce** [comment]
已解决，问题的原因是Mac自带的php在处理图片时会有问题，解决方法有两个：
- 1、设置上传前不压缩，不添加水印，这样就只是上传，不对会图片进行处理，自然不会出问题
- 2、如果要处理图片，那就重新安装php，用brew安装即可`brew install php`。
