### ISSUE TITLE
网页面板可以加个密码验证

### ISSUE THREAD

**Issue by sevenJustFine** [xiebruce/PicUploader#19]
大神好你的这个很好用,我自己也部署到自己的服务器上了.感谢分享. 我想说的是,提个建议,可以在面板上加个密码验证,需要登录才能使用..因为设置里面不是有很多对象存储的参数嘛.

**Comment by xiebruce** [comment]
最初其实只是想本地用，写个界面方便修改参数，也没想那么多，这个功能后面再考虑吧，你暂时用[http认证](https://www.xiebruce.top/634.html)就行了，我的[文档](https://www.xiebruce.top/17.html)里也有说这个，配置了就可以用账号密码登录了，别人没账号密码也进不了你页面了：
![image](https://user-images.githubusercontent.com/13575500/63077614-79f4c100-bf6b-11e9-80d4-ed9bbaf6749e.png)

**Comment by sevenJustFine** [comment]
😄,是我文档没看仔细了..谢谢
