### ISSUE TITLE
windows7下的快捷键问题

### ISSUE THREAD

**Issue by singworld** [xiebruce/PicUploader#21]
配置 Ctrl +shift +u   只要按下Ctrl +shift 就会上传
配置Ctrl +u 成功上传一次图片后 按ctrl+任意键都会再上传
![image](https://user-images.githubusercontent.com/37404619/63442293-6e226680-c465-11e9-99cc-a1c57c2ae39e.png)

**Comment by xiebruce** [comment]
好的，有时间我看看。其实如果不是有特殊需求其实你可以用Picgo，如果需要用到PicUploader中的功能，可以把PicUploader当作Picgo的第三方图床接口，这样会方便点。

**Comment by singworld** [comment]
@xiebruce   使用picgo上传成功  但软件提示未成功 没有返回值 
![image](https://user-images.githubusercontent.com/37404619/63481922-80ce8700-c4c9-11e9-8a3e-8a76de255767.png)

**Comment by xiebruce** [comment]
@singworld 你怎么是用命令的？Picgo直接用客户端呀，你在[我的博客](https://www.xiebruce.top/17.html)里搜索这个“作为PicGo的自定义图床”，然后点进去看我怎么弄的。

**Comment by singworld** [comment]
@xiebruce 用的是客户端   图片也上传成功了  就是客户端提示未成功没返回URL   上面那个是客户端的日志
![image](https://user-images.githubusercontent.com/37404619/63485665-e2e1b900-c4d6-11e9-8149-df0d4e643ad8.png)
![image](https://user-images.githubusercontent.com/37404619/63485696-0278e180-c4d7-11e9-9f67-442cacae369b.png)
![image](https://user-images.githubusercontent.com/37404619/63485830-6f8c7700-c4d7-11e9-93e9-da908f117ae8.png)

**Comment by singworld** [comment]
发现问题了。太久没更新了。。。

**Comment by xiebruce** [comment]
好的，解决问题就好！
