### ISSUE TITLE
负载均衡之后的图片链接问题

### ISSUE THREAD

**Issue by sevenJustFine** [xiebruce/PicUploader#22]
大佬，求问下，设置多个云之后的图片记录，现在有没有可以设置实现，图片地址是代理域名，而且每个图片只显示一个记录，而不是显示多个云的域名和图片链接。

**Comment by xiebruce** [comment]
1、图片地址是代理域名 ———— 你的多个云中的最后一个云的`domain`填代理域名，最终返回的就是代理域名（因为多个域名我这取最后一个域名的）
2、每个图片显示一个记录 ———— 目前没有这个功能，后面有时间我看怎么搞一下吧

**Comment by sevenJustFine** [comment]
3q
