### ISSUE TITLE
请求增加minio开源对象存储支持！

### ISSUE THREAD

**Issue by leonyff** [xiebruce/PicUploader#24]

**Comment by xiebruce** [comment]
感谢你的建议，看了一下，这个工具不错，因为兼容s3 api，所以要支持它比较简单，目前已经完成支持，不过遇到个问题，把minio的bucket设置为public后还是无法公共读取，一访问就跳转到登录页面，我要提issue问问那边先，解决问题后就发布。

**Comment by leonyff** [comment]
@xiebruce 我这边命令行设置bucket为public，后用url直接访问没有问题！[Minio设置永久下载链接](https://github.com/xiebruce/PicUploader/issues/24#issuecomment-534853288)

**Comment by xiebruce** [comment]
没事，我提issue了，已经知道怎么回事了，调好今晚或明天发。

**Comment by leonyff** [comment]
大佬神速啊， 我markdown笔记的图片终于可以一站式解决了！

**Comment by xiebruce** [comment]
设置public还是不行，你是怎么设置的，用了这个吗？
```
mc config host add myminio http://localhost:9003 0CQ2DY14AAOI44CO2A9 ucya0Ot+GRY4wuQQifVAknM3NzprLM1fnjXU6I4 --api "s3v4" --lookup "dns"
```

**Comment by leonyff** [comment]
我尝试再docker里面搭建了web版本，使用minio返回的连接格式好像有点问题！
下面上我相关的配置：
1.首先配置了相关的参数
![image](https://user-images.githubusercontent.com/38803732/65831951-691cc680-e2f1-11e9-8a7d-826ff49e1767.png)

![image](https://user-images.githubusercontent.com/38803732/65831853-45a54c00-e2f0-11e9-92f9-73f524741ef0.png)
2. 然后这个是我上传图片返回的地址：
![image.png](http://10.0.0.13:5353/2019/09/29/94e3c8a2c63a6e12099b2473f4e9c6d8.png)
选择图片
![image](https://user-images.githubusercontent.com/38803732/65831882-96b54000-e2f0-11e9-8262-eb89490842f7.png)

3. 我贴到Typora中测试不能正确显示图片：
![image](https://user-images.githubusercontent.com/38803732/65831911-da0fae80-e2f0-11e9-8467-e971b785fc58.png)
4. 我把返回的地址路径中添加bucket就正常显示了！
![image](https://user-images.githubusercontent.com/38803732/65831932-1e9b4a00-e2f1-11e9-8b45-bedffe522ce8.png)

大佬能否修复下！多谢了！

**Comment by xiebruce** [comment]
确实是有这问题，因为我这边没弄成功外链，所以没测，现在已经更新了，你更新试试！

**Comment by leonyff** [comment]
我先在内网用ip测试呢！我更新了，但是web页面都打不开了！
使用上一个版本访问web没有问题！配置什么的没有改！
这个是nginx error的日志报错信息！
```txt
2019/09/30 19:17:13 [error] 30#30: *35 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected 'region' (T_STRING), expecting ']' in /var/www/PicUploader/config/config.php on line 367" while reading response header from upstream, client: 10.0.0.86, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.0.202:8080"
```

**Comment by xiebruce** [comment]
你有把`config.php`复制一份为`config-local.php`吗？如果有的话，把`config-local.php`的这个minio区域截图上来看看，如果没有，那就把`config.php`的这个区域截图上来看看

![image](https://user-images.githubusercontent.com/13575500/65875124-5cfc3c00-e3b9-11e9-94f8-262d4f666d40.png)

**Comment by leonyff** [comment]
这个是config.php的，你看看！ 我应该没有配置错啊！

![image](https://user-images.githubusercontent.com/38803732/65876189-47881180-e3bb-11e9-8f94-42f8be1ae655.png)

**Comment by leonyff** [comment]
我重新 用新的虚拟机 git 重新设置 没有问题了！ 返回的连接也可以了！
还有一个问题就是图片上传没有问题！但是上传视频和音频会一直显示上传中，是现在还不支持上传视频和音频么？

![image](https://user-images.githubusercontent.com/38803732/65877253-bfefd200-e3bd-11e9-8ef7-486959c398c9.png)

**Comment by xiebruce** [comment]
对，网页没有支持视频和音频，只支持图片，因为网页之前只是想写个界面方便修改配置，后来写着写着才想到加个页面上传，但不建议用网页上传，因为网页不方便呀，你截图快捷键上传，或者右击图片上传，哪个都比网页方便吧。

**Comment by leonyff** [comment]
哈哈，多谢大佬！视频和音频就手动上传写链接了反正也不多！ 准备打包个docker镜像，可以去我的群晖里面部署了，绑定个域名爽歪歪哈哈！

**Comment by xiebruce** [comment]
嗯，后面有时候我也可以把网页上传视频音频加上。

问几个问题：
1、群晖能运行docker？我知道群晖本质也是Linux，我也用过，也用ssh连进去安装过软件，但它配置比较低吧，你是黑群晖还是白群晖？
2、群晖是在家里吧？所以你的图片是要存在家里？
3、看你说视频和音频手动上传，感觉你是只想通过网页上传，本地不想搭环境的样子？
4、绑定域名后我想看下你是怎么设置的，你有博客之类的吗，会写配置过程的文章不？

**Comment by leonyff** [comment]
大佬我来回答你！
1. 我是自己配的黑群，貌似所有X86的群晖不管百的还是黑的都可以运行Docker的！
2. 我群晖在自己家里面，我通过[frp](https://github.com/fatedier/frp)工具内网穿透，绑定域名，可以在外网访问我自己家里的群晖，所以我群晖上通过Docker搭建了minio和PicUploader配合就可以实现，通过域名访问在minio存储的图片连接，只要群晖不关机，在外网图片也可以正常显示。
3. 我网页上传是想测试它的功能能否正常使用，如果都配置好了，就使用你推荐的工具自动上传了！环境使用docker打包好了，直接运行就行了！
4. 我现在还在内网用ip测试，没有绑定域名！我还没搞定呢，我也是兴趣驱动学习折腾，等我配置好了，到时可以写个配置过程发你！

**Comment by xiebruce** [comment]
哦哦好的，原来是黑群晖，那配置就不是问题了，我也不是什么大佬哈哈

**Comment by xiebruce** [comment]
对了，因为你在群晖搭建了PicUploader，你本机其实不需要搭了，只要一个文件就行，就是PicUploader里的这个文件：
```
accessorys/PicUploaderHelper/PicUploader-local.php
```

你把教程里的指向`index.php`的，改成指向这个文件就行，你可以单独把这个文件复制出来，其它的全部删掉不需要了。

**Comment by sukyz** [comment]
> 哈哈，多谢大佬！视频和音频就手动上传写链接了反正也不多！ 准备打包个docker镜像，可以去我的群晖里面部署了，绑定个域名爽歪歪哈哈！

老哥你这个docker挺好用的。。就是nginx配置文件需要改一下。不然大于2m上传出错
https://github.com/xiebruce/PicUploader/issues/8

**Comment by xiebruce** [comment]
> 我重新 用新的虚拟机 git 重新设置 没有问题了！ 返回的连接也可以了！
> 还有一个问题就是图片上传没有问题！但是上传视频和音频会一直显示上传中，是现在还不支持上传视频和音频么？
> 
> ![image](https://user-images.githubusercontent.com/38803732/65877253-bfefd200-e3bd-11e9-8ef7-486959c398c9.png)

现在网页版上传任何文件都可以了，包括视频和音频。
