### ISSUE TITLE
遇到一点困难，需要支持

### ISSUE THREAD

**Issue by lv123123long** [xiebruce/PicUploader#25]
window10，，按照你的安装说明到了Web端http://api.picuploader.com 打开是白屏，啥都没有，回去对了两遍，配置和你的可以说是一样。。。不知道什么问题，需要支持

**Comment by xiebruce** [comment]
hosts文件修改了吧？你试试：
```
ping api.picuploader.com
```
出来的是什么？？能ping通吗？截图我看看
