### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by lv123123long** [xiebruce/PicUploader#26]
一切安装好了，但是显示上传失败，window powershell显示文件上传失败，请宁帖或去日志文件查看报错信息。。。。。但是我直接拖动图片去是可以七牛云显示上传成功的。。。。。。

**Comment by xiebruce** [comment]
提问题要提供多点信息：
1、你说的window powershell显示失败，是右下角测出来的通知提示失败对吧？
2、提示失败是用快捷键上传吗？
3、提示失败后实际上文件是否上传成功？
4、提示失败后，你有没有试试粘贴一下，看粘贴出来的是什么？
5、提示让你查看日志文件，你有没有去看？日志文件里有没有什么报错信息？

你什么信息都没有，就说失败，你让我怎么判断呢？
