### ISSUE TITLE
显示上传失败

### ISSUE THREAD

**Issue by yan313167** [xiebruce/PicUploader#27]
我和上一个遇到了大概是同样的上传失败问题
1，右下角显示上传失败 windows powershell
2，提示失败是用快捷键上传
3，失败后试着粘贴内容大概是这样的：![pic_xrzuhd43e8j2ahvmollca1qaw0cafh81](/)
4，日志文件没有报错信息
5，实际也没有上传成功
不知道描述的够不够，如果不够请告诉我需要什么 我尽量回答，谢谢

**Comment by yan313167** [comment]
补充一个，唯一跟教程不一样的地方是，phpstudy_pro安装成功后，WWW文件夹里面有一个error文件夹，不知道是不是这样有问题

**Comment by xiebruce** [comment]
我不知道你是用电脑网页回复还是用什么回复的，你回复的第3点，你说内容大概是“这样的”，但是内容呢？根本就看不见呀，难道你提交后看不出来的吗？
![image](https://user-images.githubusercontent.com/13575500/66245212-f7080f80-e73e-11e9-8862-bca665306a37.png)

又或者难道只是我看不见？而你可以看见？应该不会这样吧？

**Comment by yan313167** [comment]
显示失败后 我粘贴 就显示后面一串字母，我粘贴在后面的 就没有别的了------------------ 原始邮件 ------------------
发件人: "Bruce Xie"<notifications@github.com>
发送时间: 2019年10月5日(星期六) 上午7:10
收件人: "xiebruce/PicUploader"<PicUploader@noreply.github.com>;
抄送: "yan313167"<313167404@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiebruce/PicUploader] 显示上传失败 (#27)



我不知道你是用电脑网页回复还是用什么回复的，你回复的第3点，你说内容大概是“这样的”，但是内容呢？根本就看不见呀，难道你提交后看不出来的吗？
 
 
又或者难道只是我看不见？而你可以看见？应该不会这样吧？
 
&mdash;

**Comment by xiebruce** [comment]
啊？你那个看上去就是截图啊，我以为是图片没有显示呢，这也太奇怪了，你方便的话我远程帮你看看吧，但是你需要用安装一个teamviewer，注册，登录，然后把你的码发上来，不知道你用过没

**Comment by yan313167** [comment]
我用过，真的是太感谢了，想问下加个什么方式的好友方便联系？------------------ 原始邮件 ------------------
发件人: "Bruce Xie"<notifications@github.com>
发送时间: 2019年10月5日(星期六) 上午8:06
收件人: "xiebruce/PicUploader"<PicUploader@noreply.github.com>;
抄送: "yan313167"<313167404@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiebruce/PicUploader] 显示上传失败 (#27)



啊？你那个看上去就是截图啊，我以为是图片没有显示呢，这也太奇怪了，你方便的话我远程帮你看看吧，但是你需要用安装一个teamviewer，注册，登录，然后把你的码发上来，不知道你用过没
 
&mdash;

**Comment by xiebruce** [comment]
就微信吧：xiediebruce

**Comment by yan313167** [comment]
18550210178 我微信 ------------------ 原始邮件 ------------------
发件人: "Bruce Xie"<notifications@github.com>
发送时间: 2019年10月5日(星期六) 上午8:22
收件人: "xiebruce/PicUploader"<PicUploader@noreply.github.com>;
抄送: "yan313167"<313167404@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xiebruce/PicUploader] 显示上传失败 (#27)



就微信吧：xiediebruce
 
&mdash;
