### ISSUE TITLE
我本想在linux服务器上直接使用所以现在本机mamp的php环境下测试下，但是打开首页提示找不到图片？

### ISSUE THREAD

**Issue by ws1227** [xiebruce/PicUploader#28]
我本想在linux服务器上直接使用所以现在本机mamp的php环境下测试下，但是打开首页提示找不到图片？

**Comment by xiebruce** [comment]
1、报错界面截图出来看看；
2、用的是nginx还是apache？把对应的配置文件贴出来；
3、找找nginx或apache的log，贴出来看看；
