### ISSUE TITLE
怎么debug呢

### ISSUE THREAD

**Issue by txl263** [xiebruce/PicUploader#31]
怎么debug呢，用Chevereto自建的图床，没有上传成功，也没有返回错误

**Comment by xiebruce** [comment]
log目录里有日志

**Comment by txl263** [comment]
咦，配置里'logPath' => 'desktop',但是桌面没有，然后也没有logs目录

**Comment by xiebruce** [comment]
没有logs目录就是没权限创建，你是什么系统？

**Comment by txl263** [comment]
忘了说了 MACOS catalina

**Comment by xiebruce** [comment]
你是右击上传吗？没有logs目录，那就是没有权限生成，把整个目录的权限改成你当前用户应该就行了，假设你的用户名叫`zhangsan`，那么可以用这个命令：`chown -R zhangsan:staff ./PicUploader`，但是要先`cd`进入到PicUploader所在的目录中

**Comment by txl263** [comment]
是右键上传的，这个目录的权限应该没问题，因为操作都是这个账户在终端操作的，天生就是属于这个用户的

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xiebruce** [comment]
这个东西不要应该，要确认，你直接看下，现在PicUploader目录的所有者和所属组，`ls -l | grep PicUploader`就能看，比如我的所有者就是`bruce`(即我的用户名)和`staff`（用户的文件所属组一般都是`staff`）
![image](https://user-images.githubusercontent.com/13575500/70539334-80541c00-1b9e-11ea-983f-a7d4a42e6b73.png)

**Comment by txl263** [comment]
嗯嗯   确认权限没问题
#l www/PicUploader     
````                                                                                            
total 400
drwxr-xr-x  20 Eric  staff   680B 12 10 22:35 .
drwxr-xr-x   4 Eric  staff   136B 12 10 22:11 ..
-rw-r--r--@  1 Eric  staff   8.0K 12 10 22:37 .DS_Store
drwxr-xr-x  12 Eric  staff   408B 12 10 22:48 .git
-rw-r--r--   1 Eric  staff   662B 12 10 20:23 .gitignore
-rw-r--r--   1 Eric  staff   1.0K 12 10 20:23 LICENSE
-rw-r--r--   1 Eric  staff   6.1K 12 10 20:23 README.md
drwxr-xr-x   5 Eric  staff   170B 12 10 20:23 accessorys
drwxr-xr-x   3 Eric  staff   102B 12 10 20:23 common
-rw-r--r--   1 Eric  staff   680B 12 10 20:23 composer.json
-rw-r--r--   1 Eric  staff    87K 12 10 20:23 composer.lock
drwxr-xr-x   5 Eric  staff   170B 12 10 20:50 config
-rw-r--r--   1 Eric  staff   2.7K 12 10 20:23 dashboard.php
-rw-r--r--   1 Eric  staff    66K 12 10 20:23 favicon.ico
-rw-r--r--   1 Eric  staff   6.1K 12 10 20:23 index.php
drwxr-xr-x  12 Eric  staff   408B 12 10 20:23 settings
drwxr-xr-x  11 Eric  staff   374B 12 10 20:23 static
drwxr-xr-x   5 Eric  staff   170B 12 10 20:23 thirdpart
drwxr-xr-x  28 Eric  staff   952B 12 10 20:23 uploader
drwxr-xr-x  32 Eric  staff   1.1K 12 10 20:23 vendor
````

**Comment by xiebruce** [comment]
那你点上传后，那个转动的齿轮消失后，你有没有试着粘贴一下，看能粘贴出什么内容不？

**Comment by txl263** [comment]
第一句就说啦，返回的是空的。
话说，我觉得是不是PHP的问题。
装Chevereto的时候就搞不定目录的权限问题。。。。后来干脆下了docker。。。

**Comment by xiebruce** [comment]
哦，我知道问题了，你把`index.php`里的`error_reporting(0);`这句注释掉，就会报错了，忘了屏蔽了错误。

**Comment by xiebruce** [comment]
有报错，就知道问题出在哪儿了

**Comment by txl263** [comment]
define("KS3_API_LOG",FALSE);这个也得改吧

**Comment by xiebruce** [comment]
这个不用啊，你就注释我说的那句，然后再试着右键上传，然后应该就有logs目录了，然后你去里面看看是什么报错，或者你粘贴出来有可能也有错误

**Comment by txl263** [comment]
还是没有呢

**Comment by xiebruce** [comment]
那只能调试代码了，我也猜不出哪儿有问题了，你方便的话，我可以远程帮你调调看，用teamviewer，直接把id和密码在这回复上来，我连上后，再删掉就行

**Comment by txl263** [comment]
我自己去看看代码先，搞不定再问你。谢谢啊

**Comment by xiebruce** [comment]
好的，不客气！或者，你可以试试上传到github，或者其它的地方，看行不行，我试了一下，我这边上传到Chevereto是没问题的。对了，你php是什么版本？要用7.0以上的，不然不行的

**Comment by txl263** [comment]
我用的7.2

**Comment by txl263** [comment]
好，我先试试别的图床

**Comment by xiebruce** [comment]
嗯，那就不是php版本问题

**Comment by ncepuwanghui** [comment]
注释掉index.php里的第一句error_reporting(0);后，上传完成后，粘贴链接会出现如下信息
```
Notice: Undefined index: useOriginalName in /Users/samwong/workspace/software/PicUploader/uploader/UploadCloudinary.php on line 48

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /Users/samwong/workspace/software/PicUploader/vendor/cloudinary/cloudinary_php/src/Cloudinary.php on line 529

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /Users/samwong/workspace/software/PicUploader/vendor/cloudinary/cloudinary_php/src/Cloudinary.php on line 567
```
@xiebruce

**Comment by xiebruce** [comment]
你是不是用了老的config.php文件？(如果你以前用着，后来我更新了，但是你没有更新这个文件，就会有这个问题)，你试试拿最新的config.php文件复制到config-local.php里，再重新修改你要修改的参数，再试试

**Comment by ncepuwanghui** [comment]
> @ncepuwanghui
> 你是不是用了老的config.php文件？(如果你以前用着，后来我更新了，但是你没有更新这个文件，就会有这个问题)，你试试拿最新的config.php文件复制到config-local.php里，再重新修改你要修改的参数，再试试

没有，我pull的最新的master分支代码，只注释了index.php中error_reporting(0);这一行。

![image](https://user-images.githubusercontent.com/6895399/71831087-22561e00-30e3-11ea-9ec1-a92cfaba6408.png)
![image](https://user-images.githubusercontent.com/6895399/71831174-53cee980-30e3-11ea-8aef-f0f340f7923f.png)
![image](https://user-images.githubusercontent.com/6895399/71831323-a01a2980-30e3-11ea-8cff-312fcc615ddc.png)

**Comment by xiebruce** [comment]
@ncepuwanghui 不好意思，确实是我这边的问题，已修复，你更新一下就可以了

**Comment by ncepuwanghui** [comment]
> @ncepuwanghui 不好意思，确实是我这边的问题，已修复，你更新一下就可以了

客气了，非常感谢分享，已经可以正常使用了

**Comment by xiebruce** [comment]
@ncepuwanghui 好的

**Comment by Yakatosh** [comment]
你好, 我也是自建的Chevereto, 右键上传后显示失败。这是第一次的log:
![image](https://user-images.githubusercontent.com/32131698/72272001-dd8e3200-3662-11ea-95cf-11bca5459536.png)
似乎是依然用的默认smms图床? 我把config中的config.php删掉, 只留了config-local.php, 再次上传后, log是:
![image](https://user-images.githubusercontent.com/32131698/72272086-06162c00-3663-11ea-893a-2cbbf8edbaae.png)
这个curl错误命令的解释我看了, 是: Nothing was returned from the server, and under the circumstances, getting nothing is considered an error.
请问这是怎么回事呀? btw我用的是在本地配置, php版本7.3.9

**Comment by Yakatosh** [comment]
你好, 我也是自建的Chevereto图床, 按doc配置后, Mac上右键上传后报错:
2020-01-14 00:24:14 (Chevereto) => Client error: `POST http://pic.ysoph.pp.ua/api/1/upload` resulted in a `400 Bad Request` response:
{"status_code":400,"error":{"message":{},"code":false,"context":null},"status_txt":"Bad Request"}

请问这是什么原因啊? 我在想是跟我网站开了强制HTTPS有关系嘛?

**Comment by xiebruce** [comment]
@Yakatosh 你自己直接在你的chevereto图床里可以正常上传吗？

**Comment by Yakatosh** [comment]
可以的, 而且就是同一张图片

**Comment by xiebruce** [comment]
@Yakatosh 我这里试是没问题的，你的chevereto是最新的吗？我用的应该不是最新的，另外你知道怎么看版本吗？我没找到在哪个地方看版本，有可能你是最新的有问题吧，我待会试试更新一下是不是因为新版本的问题，但我感觉新版本应该是更新功能而不会去修改接口呀

**Comment by Yakatosh** [comment]
我用的是最新的1.1.4版本的Chevereto Free。看版本的话, 打开它的Dashboard就能看到了
![image](https://user-images.githubusercontent.com/32131698/72316890-84f67d80-36d2-11ea-89ad-1d182b46543a.png)
好的, 麻烦你了! 虽然我也觉得应该不是这个问题...

**Comment by xiebruce** [comment]
我更新到1.1.4了，没问题，我这里还是正常，你再确认一下，你的accessKey填的对不对

**Comment by Yakatosh** [comment]
谢谢了, 找到问题了...Chevereto API调用是视为游客的。而我在设置里把模式设置为private, 只有注册用户才能用....把private改成public就可以用了。难怪每次都干脆的 Bad Request

**Comment by xiebruce** [comment]
@Yakatosh 好的，解决了就好
