### ISSUE TITLE
JPG格式图片名称提取错误

### ISSUE THREAD

**Issue by ncepuwanghui** [xiebruce/PicUploader#33]
@xiebruce 如下图，png后缀的图片，文件名称提取正常，但是JPG格式图片文件名提取是包含了文件后缀名
![image](https://user-images.githubusercontent.com/6895399/72088140-904d5000-3344-11ea-9766-18a3916e93b8.png)
![image](https://user-images.githubusercontent.com/6895399/72088203-a78c3d80-3344-11ea-8675-0e6c50b312d7.png)
![image](https://user-images.githubusercontent.com/6895399/72088368-fc2fb880-3344-11ea-8096-d66d6e2edce9.png)

**Comment by xiebruce** [comment]
已修复，你更新一下就可以了
