### ISSUE TITLE
您好，我在设置完成之后，提醒没有文件可上传！

### ISSUE THREAD

**Issue by getidea98** [xiebruce/PicUploader#36]
![image](https://user-images.githubusercontent.com/49109682/73645385-2cebdf00-46b2-11ea-9e10-f778cf0a2b7f.png)

**Comment by xiebruce** [comment]
1、你有先截图再按快捷键吗？截图是把截图复制到剪贴板，而不是保存文件哦。
2、快捷键上传有Alfred和python两种方法，你配置的是哪种？

**Comment by getidea98** [comment]
现在可以了，谢谢

**Comment by xiebruce** [comment]
好的！
