### ISSUE TITLE
linux服务器搭建问题

### ISSUE THREAD

**Issue by ctycode** [xiebruce/PicUploader#37]
大佬您好，在linux服务器搭建好后，进入主页面，无论点击那个按钮都弹出让保存[图片](https://s2.ax1x.com/2020/02/06/16lpA1.png)

**Comment by xiebruce** [comment]
不应该呀，截图看看，最好是gif图

**Comment by ctycode** [comment]
![屏幕录制2020-02-11上午9 50 26](https://user-images.githubusercontent.com/56985178/74206152-0ed73d80-4cb5-11ea-80b9-3538f0edacc5.gif)
一直这样

**Comment by xiebruce** [comment]
@ctycode 你打开控制台，调试一下看看：在网页上右击→审查元素→网络，然后随便点击一下页面上可以点的地方，你会看到有一个请求，看看“preview(预览)”里面返回的是什么错误，肯定是返回错误了才没反应的。
![demo.gif](https://user-images.githubusercontent.com/13575500/74239537-0150a080-4d13-11ea-8c6a-7a078769a40f.gif)

**Comment by ctycode** [comment]
<br />
<b>Parse error</b>:  syntax error, unexpected '?' in <b>/www/PicUploader-master/settings/dispatch.php</b> on line <b>16</b><br />

报这个错误

**Comment by xiebruce** [comment]
@ctycode 你php版本太低了，装7.0以上的就好了

**Comment by ctycode** [comment]
原来是这样，谢谢大佬
