### ISSUE TITLE
远端ngnix配置后，访问502 Bad Gateway

### ISSUE THREAD

**Issue by GrayXu** [xiebruce/PicUploader#38]
环境：php 7.3, ubuntu 18.04, nginx Tengine 2.2.4

跟着他人[blog](https://www.uud.me/qiwenzalun/picuploader.html)配置的。

检查了www权限，nginx配置文件也照着官网文档进行的设置。  
访问结果只能获取到favicon，然后get http1.1就是502...

不然能不能打个docker啥的。。

**Comment by GrayXu** [comment]
已找到了一个可用docker，[leonyff/picuploader](https://hub.docker.com/r/leonyff/picuploader)

**Comment by xiebruce** [comment]
访问502肯定就是你nginx配置问题了，尝试解决一下，你找到的这个docker里的PicUploader版本肯定没跟上我更新的，我有时间搞一个吧。

**Comment by GrayXu** [comment]
这个版本的docker目前跟到了上上个版本（2019-10-21 v2.8.4）。谢谢作者辛苦了
