### ISSUE TITLE
Mac 版说明的右键上传问题

### ISSUE THREAD

**Issue by ysmintor** [xiebruce/PicUploader#39]
![image](https://user-images.githubusercontent.com/7165048/75843275-bc012980-5e0d-11ea-945c-4acd8b9813db.png)

---
这个视频已经打不开了，能否再传一次。
看了两次文档，没有搞清楚。我需求的是将 PHP 部署在远程主机。前后端分离的情形下，将服务端部署在远程主机，为了添加右键上传还需要在客户端安装一个 PHP 吗？因为是了 Alfred 上传的代码用到了 php 的脚本。
这一块还需要解释下。

**Comment by xiebruce** [comment]
视频你右击，复制视频地址，然后在网页中单独打开这个地址试试，不会失效的，打不开你再回复我，我这边看是没问题，能正常看的。

至于本地，你不需要装php，因为Mac自带就有，但是远程部署的话只能用网页版以及作为接口用，如果你要使用Alfred，那本地还得部署一份，这跟你的初衷可能相违背(因为你想远程部署就是不想在本地部署吧)，但是你想啊，你想截图快捷键直接上传，那肯定要本地有程序来响应的，不然怎么能把图片上传到远程服务器上呢，所以本地一定是要一个客户端的，我文章上也有说，你除了可以用PicUploader本身作客户端，还可以使用其它软件作客户端，比如：PicGo, Mweb, uPic，我最推荐的是Mweb，最方便，写文章也直接在Mweb上写，而且不用截一张传一张，而是等整篇文章完全写好再来传。

**Comment by ysmintor** [comment]
你的网页做了限制，无法单独打开。可以贴下视频地址链接吗。

我确实有在用 PicGo 和 MWeb，将使用场景可能不限于在 MWeb 中写文章，比如在论坛需要使用图片，就这个时候比如快捷方式就是找到图片右键上传（此种场景应该可以用 PicGo 实现吧，但那web-uploader 的插件支持删除吗？因为官方的 Github 就是删除没同步，我才选择用 GithubPlus 插件）。

---
另外呢也是最近在搞图床，想以最低成本又能容量大，风险小的文案。有个不限流量远程主机，也想与你讨论下。
1. 使用 PicGo + GithubPlus 插件+ jsdelivr(这家 CDN 在中国大陆也有服务器 ) 使用上可配合水印插件(还未尝试)算比较好的文案。国内图片打开速度上至少有保障，在 Github 上托管文件不怕丟。但控制性不高，别人可以简单 Clone 。容量有上限，备份自动化可能没有那么容易。
2. 使用 Chevereto  + Rclone 挂载 GDrive 或 OneDrive ，容量可以很大，使用自身的 VPS 流量，由于在海外，速度上没那么快，也不能使用 jsdelivr 这个 CDN 加速。这个方案我还没去实践，体验过可能才更清楚其中的问题。
3. 使用 OneIndex，将 OneDrive 的链接作为外链（也是我在另外一个帖子里留言的原因，如果能开发就更方便，可以批量方便上传图片）好处是使用的是微软的流量，不好也是微软最近好像改线路绕美国，除非用世纪互联版。
4.  图片做好了，其实也想有时候外链一些视频，应该配合ffmpeg 压缩，而 PicGo 我试过好像是不支持其它格式，而你这个没做格式的限制，我觉得上传上去，链接能打开，应该就可以使用，也是想尝试这个作品的一部分原因。

**Comment by xiebruce** [comment]
哦，我忘了不让右击，但其实你可以在文章区域外边右击->审查元素或按快捷键打开控制台，然后在元素里找到地址哈哈，现在给你贴出来了：[添加右键上传菜单](https://img.xiebruce.top/2019/08/28/bcffc0b11d4f0901352259d114da2ac1.mp4)

1、用github有上限，而且像你说的，别人能简单的clone，我自己用肯定不会这么用。
2、这种方案在国内基本上不行，首先google drive一般人就访问不了，而onedrive其实也是有点问题，有时候我登录不扶墙都上不去
3、像第2点所说，图片访问慢且有时候可能访问不了
4、我最初也是限制图片的，后来我发现，我不仅有上传视频的需求，还有上传压缩包等(反正就是多媒体文件之外的文件类型)，所以我觉得不应该限制，最后我就放开了限制，你可以上传任何类型文件，只要对应的存储端支持就行

**Comment by ysmintor** [comment]
感谢讲解！
