### ISSUE TITLE
建议写个简单的readme 使用说明

### ISSUE THREAD

**Issue by cscli** [xiebruce/PicUploader#41]
https://www.xiebruce.top/17.html 这里写的说明很全，但首次看显得啰嗦，可以写个傻瓜式的使用说明，后面写上“read more” ->指向https://www.xiebruce.top/17.html

**Comment by xiebruce** [comment]
@cscli 可以，感谢建议！

**Comment by xiebruce** [comment]
@cscli 已写简单readme.
