### ISSUE TITLE
方便添加md5验证吗? 

### ISSUE THREAD

**Issue by o1f** [xiebruce/PicUploader#43]
有时候重复上传图片...

**Comment by xiebruce** [comment]
可以，感谢建议！

**Comment by xiebruce** [comment]
@o1f 忘了说，md5验证图片重复功能已经添加了

**Comment by o1f** [comment]
我已经更新了...

**Comment by xiebruce** [comment]
@o1f 嗯，如果原来的记录不多，建议删除掉数据库文件(db/PicUploader.db)，删掉再上传它会重新生成，新的字段类型什么的会好点！

由于同一张图片先后两次添加水印或压缩后的md5值会不同，所以只有设置为不压缩，不添加水印，才能识别出相同图片！

**Comment by o1f** [comment]
我重装了一下,md5不好使了
设置图
https://cdn.jsdelivr.net/gh/o1f/stcResources@master/images/2020/05/31/Ts8CYigv.png
同一张图,与本地对比,大小一致,
https://cdn.jsdelivr.net/gh/o1f/stcResources@master/images/2020/05/31/TRH40RcJ.png

**Comment by xiebruce** [comment]
@o1f 
- 我最近没修改，按道理应该不至于失效，大小一致不表示md5一致；
- 你就同一张图上传两次，也不会返回前一次的url吗？当然文件名可以不同；
- 比如你有一张图：`a.jpg`，你先上传它，然后把这张图重命名为`b.jpg`，按道理这张图是不会被重复上传而是会返回之前`a.jpg`的链接（这个链接在上传历史里是有的）。
- 注意，一张图如果你上传到其它地方再下载，即使大小一样md5值也有可能不同；
- 你可以自己用其它方式获取到两张图片的md5值自己手动对比一下试试是不是一样(可参考[这里](http://blog.chinaunix.net/uid-20613650-id-3269470.html?_t_t_t=0.9654467523562034))

**Comment by xiebruce** [comment]
@o1f 好了，你更新一下就行了！

**Comment by o1f** [comment]
感谢~ 已正常~

**Comment by xiebruce** [comment]
@o1f 好的，正常就好！
