### ISSUE TITLE
www.xiebruce.top 这个网站进不去诶....

### ISSUE THREAD

**Issue by shadowfish07** [xiebruce/PicUploader#45]

**Comment by shadowfish07** [comment]
显示响应时间过长

**Comment by xiebruce** [comment]
@shadowfish07 网站本身肯定是没问题的，因为我一直都用着。建议先用手机流量进去看能不能进？

在电脑上ping一下域名看看能ping通不？ping不通的话，把它加入你代理工具的pac里吧，因为是走的国外免费cdn，在不同时间可能出现有些地区或某些网络无法ping通cdn服务器。

**Comment by shadowfish07** [comment]
嗯嗯，手机流量是可以的，电脑ping不通

**Comment by xiebruce** [comment]
@shadowfish07 那说明你所在的地方的网络对我所使用的那个cdn不通了，一般过几天，或者一周就又可以了，现在要看，只能暂时加入到代理工具pac里了，包括我自己也这样。

**Comment by shadowfish07** [comment]
嗯嗯，好
