### ISSUE TITLE
文件名格式{origin}未移除文件扩展名，出现扩展名重复

### ISSUE THREAD

**Issue by ncepuwanghui** [xiebruce/PicUploader#47]
文件名格式：{origin}-{Y}{m}{d}{H}{i}{s}
实际文件名：test.jpg-20200518235024.jpg

文件名格式：{Y}{m}{d}{H}{i}{s}-{origin}
实际文件名：202005182350240-test.jpg.jpg

@xiebruce 建议origin只提取主文件名，辛苦了

**Comment by xiebruce** [comment]
@ncepuwanghui 感谢提醒，其实一开始我是用的不带扩展名的，后来因为其它原因又把扩展名带上了，因为自己不使用`{origin}`，所以没发现这处错误，现在已经修正了，你更新一下就行。

**Comment by ncepuwanghui** [comment]
> @ncepuwanghui 感谢提醒，其实一开始我是用的不带扩展名的，后来因为其它原因又把扩展名带上了，因为自己不使用`{origin}`，所以没发现这处错误，现在已经修正了，你更新一下就行。

这么速度，给力👍🏻

**Comment by xiebruce** [comment]
@ncepuwanghui 因为这个容易修改哈哈。对了，不知道你有没有点star，如果没有，还忘能给个star支持一下哈哈。

**Comment by jack9603301** [comment]
测试

**Comment by ncepuwanghui** [comment]
> @ncepuwanghui 因为这个容易修改哈哈。对了，不知道你有没有点star，如果没有，还忘能给个star支持一下哈哈。

很早就star了😀

**Comment by xiebruce** [comment]
@ncepuwanghui 好的，感谢star!
