### ISSUE TITLE
关于对接gitee仓库

### ISSUE THREAD

**Issue by xlc520** [xiebruce/PicUploader#48]
搭建后返回的链接是这样的：
`![wish.jpg](https://gitee.com/img/wish.jpg)`
但这个不是真正的图片地址，虽然上传成功了。
用其他软件搭建gitee返回的地址是：
`![](https://gitee.com/xulch/blogimg/raw/master/img/zuihuai.jpg)`
这个地址可以用。
### 请问对接gitee的详细参数该怎么写？

**Comment by xiebruce** [comment]
[这里](https://www.xiebruce.top/17.html#i-5)有：
![image](https://user-images.githubusercontent.com/13575500/82449179-66b7e880-9add-11ea-8093-e4bd36bf4ae7.png)

**Comment by xlc520** [comment]
终于解决，强大的图床工具，点赞！

**Comment by xiebruce** [comment]
@xlc520 解决了就好，感谢star！
