### ISSUE TITLE
Github存储报错，麻烦看一下

### ISSUE THREAD

**Issue by kevin00chen** [xiebruce/PicUploader#5]
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10004 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /usr/local/software/PicUploader-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /usr/local/software/PicUploader-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /usr/local/software/PicUploader-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /usr/local/software/PicUploader-master/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /usr/l in /usr/local/software/PicUploader-master/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 185

**Comment by xiebruce** [comment]
@kevin00chen 这个一直都是正常的，超时的话，你用代理再试试，墙内github有时确实有点不稳定。配置文件里的这句注释打开，当然要你本机有科学上网工具，并且冒号后面的是端口要跟你的科学上网工具的http端口对应上：
```
'proxy' => 'http://127.0.0.1:1087',
```

**Comment by kevin00chen** [comment]
我这里访问github挺快的，公司网络可以直接翻墙的。。。

**Comment by xiebruce** [comment]
@kevin00chen 

我这里上传是正常的，另外访问接口就是一个curl请求，如果我请求接口有问题，参数有问题，或者你的token有问题什么的，那应该是返回具体报错，而不是超时，超时的原因基本上是网络问题！

虽然你公司自带翻墙，但我还是建议你换种网络试试：
1、如果你是笔记本，手机分享WIFI给电脑连试试(此时手机就要用流量了，别连公司WIFI)；
2、如果你笔记本会带回家，那么在家再试试；
3、如果你公司是台式，那么回家用自己的电脑试试；

**Comment by xiebruce** [comment]
@kevin00chen 怎么样？问题解决了吗？

**Comment by kevin00chen** [comment]
抱歉，试了几次一直都没达到期望，就没折腾了。。。
换网络，换机器都一直都报这个超时。我这两天再试试

**Comment by xiebruce** [comment]
@kevin00chen 好的，我挺好奇这是什么问题，毕竟我Mac、虚拟机里的Win10、虚拟机里的Win7、虚拟机里的Mac四个地方测试，都没有任何问题，只不过github上传相对国内的云会稍微慢一点，以下是两个上传演示：
[Mac上传gifhub演示](https://imgur.com/cCwM3HL)
[Win10上传github演示](https://imgur.com/kqnPPIB)

对了，问一下你是Mac/Win10/win7哪个系统？如果可以，麻烦把你的参数贴上来看看(access_token用*号代替)。
