### ISSUE TITLE
请问本地服务器参数要怎么填

### ISSUE THREAD

**Issue by ouyangchun1997** [xiebruce/PicUploader#51]
地址：http://192.168.1.2/
目录：/var/http/
怎么填都prefix错误。。

**Comment by xiebruce** [comment]
假设你设置prefix为`/var/http/`，`directory`为`/images/`，则最终上传路径为：`/var/http/images/`，prefix和directory都可以不存在，不存在会自动创建。

至于你说怎么填都错误，那肯定是权限不对，要上传文件到你指定的目录，需要php对该目录具有读取和写入权限，最好是php-fpm，nginx的运行用户和组，以及你要上传的目前的所有者和所属组，都是同一个，比如都是：`www`。

在我文章中搜索“**修改php-fpm运行用户和组**”和“**修改nginx的运行用户和组**”能找到修改php-fpm和nginx运行用户和组的方法，不过那是在Mac上修改的，如果是在Linux上，其实也一样，就是配置文件路径可能有所不同，你用vim打开修改就行。

文件夹的话，你这样修改就行
```bash
sudo chown -R www:www /var/http/images/
```

**Comment by ouyangchun1997** [comment]
感谢！用的群晖，去后台看了发现用户不对，改了就成功了。

**Comment by GrayXu** [comment]
> 假设你设置prefix为`/var/http/`，`directory`为`/images/`，则最终上传路径为：`/var/http/images/`，prefix和directory都可以不存在，不存在会自动创建。
> 
> 至于你说怎么填都错误，那肯定是权限不对，要上传文件到你指定的目录，需要php对该目录具有读取和写入权限，最好是php-fpm，nginx的运行用户和组，以及你要上传的目前的所有者和所属组，都是同一个，比如都是：`www`。
> 
> 在我文章中搜索“**修改php-fpm运行用户和组**”和“**修改nginx的运行用户和组**”能找到修改php-fpm和nginx运行用户和组的方法，不过那是在Mac上修改的，如果是在Linux上，其实也一样，就是配置文件路径可能有所不同，你用vim打开修改就行。
> 
> 文件夹的话，你这样修改就行
> 
> ```shell
> sudo chown -R www:www /var/http/images/
> ```

hi  
我遇到了相同的问题，指定路径下的权限为```drwxr-xr-x  2 www  www```。  
上传后，历史记录中没有，链接栏显示 ```![image.png](/)```，没有上传成功。

**Comment by xiebruce** [comment]
@GrayXu 你把你的具体信息说一下，比如，你要上传到哪个目录，你填的参数是怎样的？

**Comment by GrayXu** [comment]
> @GrayXu 你把你的具体信息说一下，比如，你要上传到哪个目录，你填的参数是怎样的？

我填写的参数如下：

prefix: /www/wwwroot/picuploader
directory: /images/{Y}/{m}/{d}/
domain: https://grayxu.cn/

picuploader文件夹已经创建，权限为```drwxr-xr-x 2 www www```。

**Comment by xiebruce** [comment]
@GrayXu 再用`ps aux | grep php-fpm`看看你php进程

**Comment by GrayXu** [comment]
> @GrayXu 再用`ps aux | grep php-fpm`看看你php进程

我的版本是dockerhub上的镜像，是19年11月后的版本。
php进程信息如下：
```
    8 root      1:57 {php-fpm7} php-fpm: master process (/etc/php7/php-fpm.conf
   10 nginx     0:29 {php-fpm7} php-fpm: pool www
   11 nginx     0:22 {php-fpm7} php-fpm: pool www
```

**Comment by xiebruce** [comment]
哦，不是最新版本呀，那你用最新版本吧，之前的版本，我也不确定有没有问题，你去docker里手动把Picuploder替换为最新就行

**Comment by GrayXu** [comment]
> 哦，不是最新版本呀，那你用最新版本吧，之前的版本，我也不确定有没有问题，你去docker里手动把Picuploder替换为最新就行

更新后有提示错误具体原因了，设置成功了，感谢！

**Comment by xiebruce** [comment]
@GrayXu 不客气！恭喜成功！
