### ISSUE TITLE
Github图床上传失败

### ISSUE THREAD

**Issue by kimix102** [xiebruce/PicUploader#52]
cURL error 7: Failed to connect to api.github.com port 443: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Web服务器安装PicUploader GitHub上传图片报错怎么解决

**Comment by xiebruce** [comment]
这个报错看上去是无法连接 api.github.com 这个域名，加个代理看看吧，毕竟github不挂代理经常抽风，或者在服务器 ping 一下api.github.com看能ping通不？

其实你可以用gitee(也就是码云)或者coding.net试试，不过gitee的缺点是不能看超过1M的图片(超过1M的图片需要查看图片者在同一个浏览器登录了gitee才行)，而coding.net有没有这个限制我就不知道了。
