### ISSUE TITLE
enhancement: support WebDAV

### ISSUE THREAD

**Issue by GrayXu** [xiebruce/PicUploader#56]
坚果云，自建NAS等都有WebDAV，是否考虑增加WebDAV呢？

**Comment by xiebruce** [comment]
如果你需要，可以增加，不过我会贴个打赏码哈哈(非固定金额，你自己输入多少就多少，但不管多少对我来说都是个鼓励！)

**Comment by GrayXu** [comment]
我想岔了，WebDAV并不能提供公链😥…不过能作为一个备份吧  
这个工具功能挺好的

**Comment by xiebruce** [comment]
> 我想岔了，WebDAV并不能提供公链😥…不过能作为一个备份吧
> 这个工具功能挺好的

感谢你的肯定！我问了，坚果云的WebDAV其实是可以提供公链的(因为他们有扩展这个功能)，只不过坚果云不对个人用户开放，要团队版才可以！

另外，WebDAV对于要分文件夹存储来说(比如自动按年月日分)，非常不方便，它不支持递归创建文件夹，必须自己多次调用接口，逐级创建，非常的慢，貌似也不支持覆盖，每次上传前，我还要查一遍目录或文件是否存在。

但即使这样，我还是实现了能自动创建多级目录的文件上传(到坚果云)，我已经上传代码，你可以更新试试，不过返回不了链接，毕竟个人版没有提供接口，但是你自己去网页端分享，还是能拿到公链的，但不是直接的，而是要自己去网页元素里找，如果要用程序拿，需要模拟登录，而登录还有图形验证码，这个不好弄，就没去研究！
