### ISSUE TITLE
请问使用Gitlab上传图片无反应怎么排查

### ISSUE THREAD

**Issue by China-JasonW** [xiebruce/PicUploader#57]
我在linux服务器上运行起来了，但是上传图片是一直等待无法成功，另外项目的日志中无其他报错，只有api.picuploader.com.access.log和api.picuploader.com.error.log两个日志文件，无法查看失败原因

**Comment by xiebruce** [comment]
1、打开网页控制台→网络(network)→清空一下→上传图片，就能看到它的请求返回什么报错；
2、PicUploader里有个logs目录，去里面找到对应日期的错误日志，看一下。

**Comment by China-JasonW** [comment]
多谢答复，网页控制台报如下错误：<b>Fatal error</b>:  Uncaught Ks3ClientException: please install curl extension in /home/grampus/PicUploader/thirdpart/ks3-php-sdk/Ks3Client.class.php:46
Stack trace:
#0 /home/grampus/PicUploader/index.php(39): require()
#1 {main}
  thrown in <b>/home/grampus/PicUploader/thirdpart/ks3-php-sdk/Ks3Client.class.php</b> on line <b>46</b><br />
这个是权限问题吗？

**Comment by xiebruce** [comment]
你php没有安装curl扩展，装的什么版本？php一般7.0以上的都是自带curl的，而且要求必须装7.0以上的，因为我写的一些语法需要7.0以上的才支持，你可以装7.3或7.4

**Comment by China-JasonW** [comment]
我装的是 7.4.13

**Comment by xiebruce** [comment]
那你查一下，为什么没有curl，用`php -m | grep curl`可以看有没有curl，如果有就会输出curl，如果没有，那就是空

**Comment by xiebruce** [comment]
或者写一个简单的php页面，页面里写上
```php
<?php
    phpinfo();
```
这样可以用页面的方式查看到一些信息。

**Comment by China-JasonW** [comment]
多谢，问题已解决，是因为我php安装有问题，curl版本和libcurl版本太新了导致的

**Comment by xiebruce** [comment]
好的，解决了就好
