### ISSUE TITLE
PicUploader Dcker web服务器安装，搭配本地 uPIC / Picgo 使用时出错

### ISSUE THREAD

**Issue by artxia** [xiebruce/PicUploader#59]
我将PicUploader安装在本地虚拟机，是想借助PicUploader的 `index.php` 的API能力来实现一些uPic不支持的图床。做成“PicUploader服务端+uPic客户端”的形式。
所以我自己构建了 Docker 版在虚拟机运行，日志无报错，然后本地pc使用 `ip:端口` 打开web上传测试了几个图床，一切正常。

但是当我本地配置 uPIC / Picgo 后貌似不能通信，提示失败。（检查了authorization无误；PicUploader日志无报错，看起来根本没通信）
我起初怀疑是我未绑定域名，而使用了内网 ip:端口 的原因。
然后我通过frp重新绑定了域名，测试web上传啥的都正常。但是uPIC / Picgo依旧提示失败。

请教一下，这种情况应该怎么处理？

下面两张图，第一张是`ip:端口` 的配置和错误提示；第二张是绑定域名后的配置和错误提示。
![image](https://user-images.githubusercontent.com/50513568/103124436-b3dae900-46c2-11eb-9fd9-837fbe4c1516.png)

![image](https://user-images.githubusercontent.com/50513568/103124324-58a8f680-46c2-11eb-87bd-d2814b5f2f72.png)

Picgo测试，得到的错误提示就是一个括弧：`{}`

**Comment by xiebruce** [comment]
docker版是别人封装的，不是最新代码，你自己进入docker里面把代码更新到最新再试试

**Comment by artxia** [comment]
> docker版是别人封装的，不是最新代码，你自己进入docker里面把代码更新到最新再试试

https://github.com/artxia/PicUploader-Docker

我自己打包的，直接拉取的最新代码

**Comment by xiebruce** [comment]
好的，那我先看看，太久不用uPic了。

**Comment by xiebruce** [comment]
@artxia 这是uPic的bug，我已经在那边提交了issue了：https://github.com/gee1k/uPic/issues/163，你可以先试试其它旧版本的uPic哪个可以用，反正我最初试的是可以的，估计后来更新的时候哪儿不小心搞错了吧。

**Comment by artxia** [comment]
> @artxia 我测试过了，这是uPic的bug，我已经在那边提交了issue了：[gee1k/uPic#163](https://github.com/gee1k/uPic/issues/163) ，你可以先试试其它旧版本的uPic哪个可以用，反正我最初试的是可以的，估计后来更新的时候哪儿不小心搞错了吧。

如果可以，还请试一下Picgo，也报错

**Comment by xiebruce** [comment]
可以，你试哪个版本呢？2.2.2还是最新的beta4?

**Comment by artxia** [comment]
2.3.0-beta.3
是版本原因么？我换发行版试试

**Comment by xiebruce** [comment]
我也不清楚，我这边用brew安装的，只能安装到稳定版，也就是2.2.2

**Comment by xiebruce** [comment]
我这边试了2.2.2版本，没问题，可以正常上传
![image](https://user-images.githubusercontent.com/13575500/103127308-387e3500-46cc-11eb-8156-6a56587c75c0.png)

**Comment by artxia** [comment]
经我测试
uPIC 0.19.6 成功了 ，20以后版本全出错
Picgo 2.2.2 我试了不成功，如你所说插件版本没变，你成功了。 那么应该是我的问题。
不过我用uPIC就行，下载picgo本就是为了这次测试 哈哈

**Comment by xiebruce** [comment]
好的，picgo新版本就等作者修复后再更新吧。

**Comment by xiebruce** [comment]
upic那边测试出来了，新版本的upic需要在`other fields`(其它选项)里添加一个`content-type`，值为`multipart/form-data;`(注意，分号不能省)
![image](https://user-images.githubusercontent.com/13575500/106098488-13ba2900-6174-11eb-8741-b268bae15c61.png)

![image](https://user-images.githubusercontent.com/13575500/106098406-f4bb9700-6173-11eb-853f-b2a73066a2f1.png)
