### ISSUE TITLE
web页面下剪贴板粘贴图片上传七牛云的时候体积会巨大，大概是10倍左右

### ISSUE THREAD

**Issue by hjthjthjt** [xiebruce/PicUploader#7]
但是如果通过本地上传的话体积正常

**Comment by xiebruce** [comment]
确实是我这边的问题，有一个地方没修改导致未压缩图片，现在已经好了，你更新代码即可，更新后如果有问题，请删除`/config/.settings`目录并重新添加配置。

**Comment by hjthjthjt** [comment]
@xiebruce 
诶我本来还以为是我的问题……
因为我自己测试的时候是很奇怪，本来是放在sm.ms的文件，在chrome无缓存的情况下，开发者工具显示的2m，右键另存为也是2m，但是如果我这时候通过右键复制（复制sm.ms的图片，在新标签打开的情况下），粘贴到QQ的时候有明显延迟，再把QQ聊天框里这张图另存为有27m。上传七牛云的时候也是这个27m……🤔
如果是你的问题按理说复制后放QQ聊天框的时候应该是2m的状态啊

**Comment by xiebruce** [comment]
前面的2M的问题，是因为你粘贴的时候，chrome浏览器会自动把剪贴板的图片存成`image.png`，不管是什么格式的图片(比如jpg，gif)都会被它转成png，所以我js是拿到chrome传给我的图片再通过ajax上传的，而chrome保存的图片会比较大，是“全分辨率”，比如我的Macbook Pro，retina屏系统显示分辨率是1440×900，但retina屏是4个点一个像素(横着两个点，竖着两个点)，所以浏览器把你截的图变成图片的长宽分别是1440×2和900×2，即2880×1800，这个图片保存起来就是2M多，差不多3M的样子，如果压缩了(压缩率50%)，最后可能剩七八百K这样。

但后面你说的27M，就肯定不是我这边的问题了，而且sm.ms最大只支持上传5M的图，27M的图就算我这边想传都传不上去，更别说它根本就不让传这么大，我实在想不出是怎么出来的，我试了一下复制并粘到QQ聊天框里，就是它本来的大小呀，你这个问题很奇怪，你是什么系统？什么版本？每次都可以重现这个问题么？
![image](https://user-images.githubusercontent.com/13575500/56454545-11af1d80-6385-11e9-9777-4a64da78ebfc.png)

**Comment by hjthjthjt** [comment]
这就是我为什么主动关闭issues的问题……我在Windows10下操作的，问题就出在为什么chrome保存到剪贴板的时候会把原来2m的体积扩充到27m……我目前几次都是变成17m+的大文件，我一开始还疑惑为什么粘贴上传会这么久，最后发现是chrome把他体积弄的很大导致上传需要更多的时间

**Comment by xiebruce** [comment]
我用win10试了一下，chrome保存的图片也才一两M，这个大小应该是跟你显示器有关的，如果你的显示器很大分辨率又高，产生的图片是27M估计也有可能，不过我也是猜的，不知道你显示器多大？什么分辨率？

**Comment by hjthjthjt** [comment]
23.6寸好像，1080P，理论不会出现这些问题……

**Comment by xiebruce** [comment]
嗯，chrome是最新吗？不是的话可以更新试试，另外用firefox试试，也一样么？IE就别试了，不支持ES6，就算IE11我用个反引号也报错。。。
