### ISSUE TITLE
关于添加Nginx密码认证的问题

### ISSUE THREAD

**Issue by xiaodongxier** [xiebruce/PicUploader#72]
大佬好，麻烦请教一个问题，就是图片选择存储到本地服务器后添加了Nginx密码认证，但是图片外链访问也需要密码认证这个正常吗？上传页面需要认证这个正常，但是如果访问外链资源也需要认证是不是不太对啊？

**Comment by xiebruce** [comment]
确实不对，外链跟上传页面，不要使用同一个域名，要分开配置，比如你的域名是：example.com，那么你的外链可以是：i.example.com或者img.example.com，而上传页面，可以是：picuploader.example.com或upload.example.com

**Comment by xiaodongxier** [comment]
哦，原来如此，感谢大佬的解答，如果是这样的话那我通过uPic等客户端上传的话，返回的链接是不是不能自动替换成i.example.com或者img.example.com？或者大佬有什么好的方案可以推荐一下吗？感谢

**Comment by xiebruce** [comment]
你看我[这篇文章](https://www.xiebruce.top/644.html)，打开可能有点慢，但是可以打开的，uPic不知道可不可以替换，但是PicUploader是可以设置替换域名的。

**Comment by xiaodongxier** [comment]
亲测可以，在配置页面配置完成后，通过uPic是上传后是可以替换域名的，感谢大佬

**Comment by xiebruce** [comment]
这样肯定可以呀，因为此时uPic只是充当一个上传客户端，它只是把文件发送给PicUploader并接收PicUploader的返回链接而已，真正上传到存储云的是PicUploader。

**Comment by xiaodongxier** [comment]
明白了，感谢哈
