### ISSUE TITLE
请问下远端主机被墙的问题

### ISSUE THREAD

**Issue by foxdodo** [xiebruce/PicUploader#75]
在php空间搭了PicUploader, 然后用CF绑了个域名而且国内能正常访问. 但是上传图片到国内coding图床都是返回超时, 然后我ping一下主机发现IP被墙了, 似乎是因为上传图片用了主机做中转, 而主机IP被墙导致上传失败, 请问这种情况不换IP还有救吗?

**Comment by xiebruce** [comment]
无救！

你picuploader搭建在国外主机，那coding那边识别到的就是从国外主机上传，既然你的主机到coding不通，那肯定是不行的。

其实就算能通，那也没啥意思，因为相当于你图片绕一圈国外，又传回国内。你既然用国内图床，为什么还要把picuploader搭建在国外主机呢，直接在自己电脑上不好吗？这样的话，你要传到coding，那都是直接国内网络，这样更快呀！

当然我也能理解，可能你多台电脑都要用，所以想着在服务器上搭建，这样在哪里都可以访问，但是在服务器上搭建确实会有你说的问题，如果换国内服务器的话，又得备案，就很烦，不行你就每台电脑上搭建一个吧🤣

**Comment by foxdodo** [comment]
好吧, 感谢大佬解答
