### ISSUE TITLE
Alfred 快捷键上传，curl总是报错

### ISSUE THREAD

**Issue by hiblacker** [xiebruce/PicUploader#83]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/22385375/217478543-fe0901e5-99d4-4afd-af58-d922513ea8a0.png">
刚配置好是可以上传的，过了一小时，截图上传，curl就开始一直报错。第一张报错图片大小是8M，换成小图片也不行，换个网络也不行。关掉网络代理还是不行。
请大佬赐教

**Comment by xiebruce** [comment]
你是上传到哪个云？

**Comment by hiblacker** [comment]
> 你是上传到哪个云？

又拍云

**Comment by hiblacker** [comment]
cURL error 35: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by hiblacker** [comment]
抱歉，终于找到问题了，没有改名字为 `config-local.php`
不过很奇怪为什么配置成功的时候上传成功了

**Comment by xiebruce** [comment]
> 抱歉，终于找到问题了，没有改名字为 `config-local.php` 不过很奇怪为什么配置成功的时候上传成功了

配置文件，.config.json优先，config-local.php次之，config.php最后，就算你不改为config-local.php，配置也是会被读取的
