### ISSUE TITLE
希望增加上传的时候自定义文件夹功能

### ISSUE THREAD

**Issue by XinAnzzZ** [xiebruce/PicUploader#9]
个人为了方便图片管理，通常都是保持和 MD 文档所在路径一致的。所以希望大佬可以增加一个  上传图片时快速指定文件夹的功能，或者可以通过配置，上传时可以通过下拉框选择已配置的文件夹列表。

**Comment by xiebruce** [comment]
这个想法可以，我找时间实现一下。

**Comment by XinAnzzZ** [comment]
谢谢大佬，辛苦大佬。

**Comment by xiebruce** [comment]
@XinAnzzZ 不客气，加上了。

先在这边设置，每行一个目录
![image](https://user-images.githubusercontent.com/13575500/57536364-a00c3300-7376-11e9-90ba-84afabdc67ed.png)

然后在这里选择要上传的目录即可，选择后自动保存，无需保存按钮，这样更方便快捷：
![image](https://user-images.githubusercontent.com/13575500/57536437-c7630000-7376-11e9-8ee3-2976100b3f93.png)

但这里修改上传目录后，右击上传，快捷键上传什么的都会使用这个修改的目录，因为配置文件都是同一个。

**Comment by XinAnzzZ** [comment]
感谢大佬，效率好高。。
